### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by r-chris** [joonvena/robotframework-docker-action#1]
I assume the documentation is largely provided through: https://github.com/ppodgorsek/docker-robot-framework, but it would nonetheless be great to add a few additional infos to the README here. I would find it particularly helpful to understand the given example, specifically what: `ROBOT_TESTS_DIR: ${{ github.workspace }}/robot_tests` and `ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports` actually mean.

Presumably `${{ github.workspace }}/robot_tests` is the directory in the source code, where all robot tests are stored and `${{ github.workspace }}/reports` is where reports will be generated (would this directory already have to exist?).

**Comment by joonvena** [comment]
Yes you are right. ${{ github.workspace }} points to workspace folder that contains the source code and the /robot_tests is the path where tests are located. I extended the documentation now to include short explanation what these variables do. Let me know if there is something else to work on.
