### ISSUE TITLE
How to configure permissions

### ISSUE THREAD

**Issue by laojala** [joonvena/robotframework-docker-action#2]
When running tests using action, I get permission error:

```
[ ERROR ] Opening output file '/github/workspace/reports/output.xml' failed: PermissionError: [Errno 13] Permission denied: '/github/workspace/reports/output.xml'
```

How to configure Docker image variables `ROBOT_UID` and `ROBOT_GID`? 

When I run container without this action, adding this gives required permissions `--user $(id -u):$(id -g)`. Example:

```
jobs:
    run_robot_tasks:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Tasks
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tasks:/opt/robotframework/tests:Z \
              -v ${PWD}/reports/file://opt/robotframework/temp/reports/file/ \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
```

**Comment by YauheniPo** [comment]
I also have this problem

**Comment by rashmigowda55** [comment]
[ ERROR ] Creating output file directory '/github/workspace/reports' failed: PermissionError: [Errno 13] Permission denied: '/github/workspace/reports'

How to solve this issue 

This is my .yml file
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/Tests/abc.robot
          REPORT_PATH: ${{ github.workspace }}/reports
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/report

**Comment by IJustDev** [comment]
Hey there,

I've spend like 20 hours crying on this problem.
I had to manually create the folder reports. Really hoping this still helps somebody.

**Comment by rashmigowda55** [comment]
> Hey there,
> 
> I've spend like 20 hours crying on this problem.
> I had to manually create the folder reports. Really hoping this still helps somebody.
> 
> My setup without the action:
> 
> ```
>         - name: test
>           run: |
>             mkdir ${{github.workspace}}/reports
>             docker run --shm-size=1g -e BROWSER=headlesschrome \
>             -v ${{github.workspace}}/e2e:/opt/robotframework/tests:Z \
>             -v ${{github.workspace}}/reports:/opt/robotframework/reports:Z \
>             --user 1001:1000 \
>             ppodgorsek/robot-framework:latest
> ```



# runs tests for push-events, for pull requests and using cron schedule:
name: Run Robot Framework Tests
on:
  pull_request:
    branches: [master]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # checkout code from a repository
      - uses: actions/checkout@v2
      # create folder for test reports
      - name: Create folder for reports
        run: mkdir reports
      # run Robot Framework tests inside Docker container
      - name: Run Robot Framework Tests
        # container used here is ppodgorsek/robot-framework:latest
        # see container documentation for usage: https://hub.docker.com/r/ppodgorsek/robot-framework/dockerfile
        # it is required that GitHub repository contains folder "reports". Commit some file inside "reports" to create it
        # place tests in folder tests or change docker run command accordingly
        # configure -e ROBOT_OPTIONS according to yout tests, or remove it if no special configuration is needed
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${{ github.workspace }}/<path to robot scripts>:/opt/robotframework/tests:Z \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest
      # upload test reports as a zip file
      - name: Upload reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image privileges.
          path: ${{ github.workspace }}/reports
      # repository name is needed for posting test report in the next step
      - name: Get Repository Name
        run: |
          export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
          echo "::set-env name=REPOSITORY_NAME::$REPO"
      # when test are run for a commit, post results as a comment
      # note: comment is not posted for tests triggered for pull requests, only for a main branch (master)
      - name: Send test report as comment to commit
        uses: joonvena/robotframework-reporter-action@v0.1
        if: ${{ github.event_name == 'push' }}
        env:
          GH_ACCESS_TOKEN: ${{ github.TOKEN }}
          REPO_OWNER: ${{ github.REPOSITORY_OwNER }}
          COMMIT_SHA: ${{ github.SHA }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
          REPORT_PATH: ${{ github.workspace }}/reports

**Comment by xNok** [comment]
Do you think it is possible to create a composite action instead that would run the docker command with the good uid gui? https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action.

Otherwise, do you see any changes that could be made to `ppodgorsek/docker-robot-framework` to be better suited for GitHub action?

It would be nicer to be able to use the action out of the box

**Comment by joonvena** [comment]
Yes, i'm currently in process of building this again and addressing the permission issues and also adding #3 as a permanent fix.

**Comment by joonvena** [comment]
I just released new version of this action which corrects the permission issues.
