### ISSUE TITLE
robot_options field

### ISSUE THREAD

**Issue by ClaudioAmyris** [joonvena/robotframework-docker-action#7]
Hi

I'm trying to send variables in the config but I can't find the correct way to send the config in the robot_options field.
I've tried
robot_options: --variable myvar:myvalue
robot_options: "--variable myvar:myvalue"
robot_options: '"--variable myvar:myvalue"'

Changing --variable for "-v" also doesn't work.
I also tried to send a simpler command like "--loglevel debug" but even that doesn't work.

Some explanation on how to send this would be helpful.
Thanks

**Comment by joonvena** [comment]
Hi, thanks for the comment. There is actually bug in the action. I'll release the fix during today.

**Comment by joonvena** [comment]
This is now fixed. You can use the options eg.
`robot_options: "--variable myvar:myvalue"`
